// data.js — Database Arsip Tidak Resmi Sakernas
// Update file ini saja untuk menambah/mengubah data.
// Format: { year, period, category, link, title, lang, note }

window.SAKERNAS_DATA = [
  { year:2004, period:"-", category:"Kuesioner", link:"https://drive.google.com/file/d/1LXIKCtMYlDTG3tc7tqGKmPgVyIWyErc8/preview", title:"2004 ENV1", lang:"ID", note:"" },
  { year:2004, period:"-", category:"Kuesioner", link:"https://drive.google.com/file/d/1qjTIqehm5hFNtmWa0P2ayywB4EJazbOn/preview", title:"2004 ENV2", lang:"ID", note:"" },
  { year:2008, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2009/11/23/069fde9ab6e06cd674e0a608/analisis-mobilitas-tenaga-kerja-hasil-survei-angkatan-kerja-nasional-2008.html", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"pertama kali terbit" },
  { year:2009, period:"Agustus", category:"Publikasi", link:"", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"tidak terbit" },
  { year:2010, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2011/12/09/27c1eafe9ae25b8775753a78/analisis-mobilitas-tenaga-kerja-hasil-survei-angkatan-kerja-nasional-2010.html", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"" },
  { year:2011, period:"Agustus", category:"Publikasi", link:"", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"tidak terbit" },
  { year:2012, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/11/04/60be1c892ff94a29ebfcc24b/analisis-mobilitas-tenaga-kerja-hasil-survei-angkatan-kerja-nasional-2012.html", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"" },
  { year:2013, period:"Agustus", category:"Publikasi", link:"", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"tidak terbit" },
  { year:2014, period:"Agustus", category:"Publikasi", link:"", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"tidak terbit" },
  { year:2015, period:"Agustus", category:"Publikasi", link:"", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"tidak terbit" },
  { year:2016, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/12/08/a85da15eb324f53f05163351/analisis-mobilitas-tenaga-kerja-hasil-survei-angkatan-kerja-nasional-2016.html", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"" },
  { year:2017, period:"Agustus", category:"Publikasi", link:"", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"tidak terbit" },
  { year:2018, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/12/09/4abf897285f4e8265346d8d7/analisis-mobilitas-tenaga-kerja-hasil-survei-angkatan-kerja-nasional-2018.html", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"" },
  { year:2019, period:"Agustus", category:"Publikasi", link:"", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"tidak terbit" },
  { year:2020, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/11/17/bf53c37506d4a38a2a700f5a/analisis-mobilitas-tenaga-kerja-hasil-survei-angkatan-kerja-nasional-2020.html", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"" },
  { year:2021, period:"Agustus", category:"Publikasi", link:"", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"tidak terbit" },
  { year:2022, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/10/27/83d4aaefa732e79efa75107b/analisis-mobilitas-tenaga-kerja-hasil-sakernas-2022.html", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/08/26/b07cde6196c248635467c2af/analisis-mobilitas-tenaga-kerja-hasil-sakernas-2023.html", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"" },
  { year:2024, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/08/22/8934c883888698d7acb2e179/analisis-mobilitas-tenaga-kerja-hasil-sakernas-2024.html", title:"Analisis Mobilitas Tenaga Kerja", lang:"ID", note:"" },
  { year:1982, period:"-", category:"Kuesioner", link:"https://drive.google.com/file/d/1CNnl9Kt42JEqDHz-BrD-1SgFqqo8kKOw/preview", title:"Bagian dari Susenas", lang:"ID", note:"" },
  { year:2018, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/12/14/646b4fb626979f3e154e63d7/booklet-survei-angkatan-kerja-nasional-agustus-2018.html", title:"Booklet", lang:"ID", note:"" },
  { year:2019, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/12/10/680c34c3a8c4955c235892c9/booklet-survei-angkatan-kerja-nasional-agustus-2019.html", title:"Booklet", lang:"ID", note:"" },
  { year:2020, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/12/23/d8b9a75ce826ddafbddb9657/booklet-survei-angkatan-kerja-nasional-agustus-2020.html", title:"Booklet", lang:"ID", note:"" },
  { year:2021, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/12/22/52d405e2dc5dc6f2ba57bf83/booklet-survei-angkatan-kerja-nasional-agustus-2021.html", title:"Booklet", lang:"ID", note:"" },
  { year:2022, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/12/22/ffb3e2d42b94d727d97e78d8/booklet-survei-angkatan-kerja-nasional-agustus-2023.html", title:"Booklet", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/12/22/ffb3e2d42b94d727d97e78d8/booklet-survei-angkatan-kerja-nasional-agustus-2023.html", title:"Booklet", lang:"ID", note:"" },
  { year:2024, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/12/20/145b7ca9b2e159c6c0493290/booklet-sakernas-agustus-2024.html", title:"Booklet", lang:"ID", note:"" },
  { year:2025, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2026/01/12/7cafd1df082c81784e0e15f8/booklet-sakernas-agustus-2025.html", title:"Booklet", lang:"ID", note:"" },
  { year:2018, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/09/28/c49b09bd9fcb72050c51958e/booklet-survei-angkatan-kerja-nasional-februari-2018.html", title:"Booklet", lang:"ID", note:"" },
  { year:2019, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/11/27/5428e1117e138c6d36769363/booklet-survei-angkatan-kerja-nasional-februari-2019.html", title:"Booklet", lang:"ID", note:"" },
  { year:2020, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/08/28/2aaf3f1339f9295704cb198f/booklet-survei-angkatan-kerja-nasional-februari-2020.html", title:"Booklet", lang:"ID", note:"" },
  { year:2021, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/08/09/790fa89d429d86821c12f57b/booklet-survei-angkatan-kerja-nasional-februari-2021.html", title:"Booklet", lang:"ID", note:"" },
  { year:2022, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/07/07/40a0b3f1fd46be1a5edbae1d/booklet-survei-angkatan-kerja-nasional-februari-2023.html", title:"Booklet", lang:"ID", note:"" },
  { year:2023, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/07/07/40a0b3f1fd46be1a5edbae1d/booklet-survei-angkatan-kerja-nasional-februari-2023.html", title:"Booklet", lang:"ID", note:"" },
  { year:2024, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/07/05/0455778ea851bbeda66890a8/booklet-sakernas-februari-2024.html", title:"Booklet", lang:"ID", note:"" },
  { year:2025, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/07/14/90a6b20c25c63176d23ab46c/booklet-sakernas-februari-2025.html", title:"Booklet", lang:"ID", note:"" },
  { year:2021, period:"Desember", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/12/22/42c332115ba2a6fb0f36590c/booklet-keselamatan-dan-kesehatan-pekerja-di-masa-pandemi-covid-19.html", title:"Booklet COVID-19", lang:"ID", note:"Booklet Keselamatan dan Kesehatan Pekerja di Masa Pandemi COVID-19" },
  { year:2002, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/1_ixIMcXGP79Q3v-cvVTYnTKkAtSIRvC5/preview", title:"Buku KBJI 2002", lang:"ID", note:"" },
  { year:2014, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/1U0tuLEMSGHPRBDTlkRkdw1YQhWpJepVC/preview", title:"Buku KBJI 2014", lang:"ID", note:"" },
  { year:2000, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/1EqX7OBRDgVfKbJ5zUv3nVrvLhTGZ1Pj_/preview", title:"Buku KBLI 2000", lang:"ID", note:"" },
  { year:2005, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/19k963QjQDUYam1vS4S4dWzk7YSFTaCfR/preview", title:"Buku KBLI 2005", lang:"ID", note:"" },
  { year:2009, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/1CbtN6AlPZiVCkvZuLWP4rALkAVPm7IY9/preview", title:"Buku KBLI 2009", lang:"ID", note:"" },
  { year:2015, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/174k2LqODmNDh46ScuTBypFv0YViLg_E7/preview", title:"Buku KBLI 2015", lang:"ID", note:"" },
  { year:2020, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/1Z1Uub1sqsAKts2RrAVA8WtSbb-kf_lEm/preview", title:"Buku KBLI 2020", lang:"ID", note:"" },
  { year:2020, period:"Agustus", category:"Publikasi", link:"https://drive.google.com/file/d/1ZCvS9M8colbXwuUj6S1jarRFsaA1i6eW/preview", title:"Gender", lang:"ID", note:"" },
  { year:2002, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/1z9SNTH6qdMqdFmxaGrH4T9BDBXql-VoE/preview", title:"Kode KBJI 2002", lang:"ID", note:"" },
  { year:2005, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2005/05/15/d5552564f92c1ae5d14b125b/keadaan-angkatan-kerja-di-indonesia-februari-2005.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2005, period:"November", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2005/05/15/d05f8cc4045647387406b2be/keadaan-angkatan-kerja-di-indonesia-november-2005.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2006, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2006/05/15/5f6c1984f09eefcb696ae432/keadaan-angkatan-kerja-di-indonesia-februari-2006.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2006, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2006/05/15/482ccf0eab5d9b8e7830bfb4/keadaan-angkatan-kerja-di-indonesia-agustus-2006.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2007, period:"Februari", category:"Publikasi", link:"", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2007, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2007/05/15/09e3ec633df0c1c87955bb29/keadaan-angkatan-kerja-di-indonesia-agustus-2007.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2008, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2008/07/08/da7e4fa23e9da199d5be185c/keadaan-angkatan-kerja-di-indonesia-februari-2008.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2008, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2009/01/21/3ad1c074557a2a558f67b879/keadaan-angkatan-kerja-di-indonesia-agustus-2008.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2009, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2009/05/15/c33f6abd0bfbb27521a5fe40/keadaan-angkatan-kerja-di-indonesia-februari-2009.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2009, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2010/01/19/21288c05094a4be978722b2a/keadaan-angkatan-kerja-di-indonesia-agustus-2009.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2010, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2010/06/04/ef529db5cb2467398d8b0c4f/keadaan-angkatan-kerja-di-indonesia-februari-2010.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2010, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2011/01/17/4a96280306b753e66d226739/keadaan-angkatan-kerja-di-indonesia-agustus-2010.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2011, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2012/02/15/7b5abecdad813abf223ce985/keadaan-angkatan-kerja-di-indonesia-februari-2011.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2011, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2011/11/28/de1341bc43b62015fe8f6bb3/keadaan-angkatan-kerja-di-indonesia-agustus-2011.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2012, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2012/06/06/8a882a96c015cb58e6717aff/keadaan-angkatan-kerja-di-indonesia-februari-2012.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2012, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2012/11/30/ff39047672c89664271a9acd/keadaan-angkatan-kerja-di-indonesia-agustus-2012.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2013, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/05/31/2f72f0bfa47eefad7654e0ca/keadaan-angkatan-kerja-di-indonesia-februari-2013.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2013, period:"Mei", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/08/30/932f5d372f9277048b11ac46/keadaan-angkatan-kerja-di-indonesia-mei-2013.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2013, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/11/29/9d047c72bf28888630d0e093/keadaan-angkatan-kerja-di-indonesia-agustus-2013.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2013, period:"November", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/02/25/c70e3a23c0b186f183d29028/keadaan-angkatan-kerja-di-indonesia-november-2013.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2014, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/05/30/f9547abb9d006af95cc7fc69/keadaan-angkatan-kerja-di-indonesia-februari-2014.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2014, period:"Mei", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/09/08/c3d8f69d99bd9c0e291baa9f/keadaan-angkatan-kerja-di-indonesia-mei-2014.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2014, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/11/28/7ea2936d8c309b4f942b79c7/keadaan-angkatan-kerja-di-indonesia-agustus-2014.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2015, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2015/06/01/094e72f95984a7d1c506fa32/keadaan-angkatan-kerja-di-indonesia-februari-2015.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2015, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2015/11/30/311dc33e7624d47529ec4800/keadaan-angkatan-kerja-di-indonesia-agustus-2015.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2016, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2016/06/01/bd60570a94b7dc84053e2be9/keadaan-angkatan-kerja-di-indonesia-februari-2016.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2016, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2016/11/30/d12d7d2096f263801ae18634/keadaan-angkatan-kerja-di-indonesia-agustus-2016.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2017, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/08/03/c1dd4d1c5e24d46f7f0cd9ef/keadaan-angkatan-kerja-di-indonesia-februari-2017.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2017, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/11/30/0daa04d8d9e8e30e43a55d1a/keadaan-angkatan-kerja-di-indonesia-agustus-2017.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2023, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/06/09/5ce5c75f3ffabce2d6423c4a/keadaan-angkatan-kerja-di-indonesia-februari-2023.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/12/08/f8c567805aa8a6977bd4594a/keadaan-angkatan-kerja-di-indonesia-agustus-2023.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2024, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/06/07/112a10c79b8cfa70eec9f6f3/keadaan-angkatan-kerja-di-indonesia-februari-2024.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2024, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/12/09/6f1fd1036968c8a28e4cfe26/keadaan-angkatan-kerja-di-indonesia-agustus-2024.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2018, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/06/04/b7e6cd40aaea02bb6d89a828/keadaan-angkatan-kerja-di-indonesia-februari-2018.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2018, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/11/30/6d8a8eb26ac657f7bd170fca/keadaan-angkatan-kerja-di-indonesia-agustus-2018.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2019, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/05/31/a96ce41f72e59d5dfb1cad9f/keadaan-angkatan-kerja-di-indonesia-februari-2019.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2019, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/11/29/96138ece33ccc220007acbdd/keadaan-angkatan-kerja-di-indonesia-agustus-2019.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2020, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/06/19/c0d3df055948f7bcb65890f0/keadaan-angkatan-kerja-di-indonesia-februari-2020.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2020, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/11/30/307a288d678f91b9be362021/keadaan-angkatan-kerja-di-indonesia-agustus-2020.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2021, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/06/08/b547a5642aeb04d071cb83d4/keadaan-angkatan-kerja-di-indonesia-februari-2021.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2021, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/12/07/ee355feea591c3b6841d361b/keadaan-angkatan-kerja-di-indonesia-agustus-2021.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2022, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2022/06/07/c81631f750ee1ece2c3eb276/keadaan-angkatan-kerja-di-indonesia-februari-2022.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2022, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2022/12/07/a64afccf38fbf6deb81a5dc0/keadaan-angkatan-kerja-di-indonesia-agustus-2022.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2025, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/06/20/fec826c9a88adaa045a6ac9f/keadaan-angkatan-kerja-di-indonesia-februari-2025.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2025, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/12/19/42a75ee61332755586fdfcdd/keadaan-angkatan-kerja-di-indonesia-agustus-2025.html", title:"Keadaan Angkatan Kerja", lang:"ID", note:"" },
  { year:2022, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2022/06/14/0ab4432ce141b3d9fac13d92/indikator-pasar-tenaga-kerja-indonesia-februari-2022.html", title:"KILM", lang:"ID", note:"" },
  { year:2025, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/12/30/cd78a8ff95fcf228a712e8ac/indikator-pasar-tenaga-kerja-indonesia-agustus-2025.html", title:"KILM", lang:"ID", note:"" },
  { year:2025, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/06/30/7cc0d8a5ea09515a0b2a2729/indikator-pasar-tenaga-kerja-indonesia-februari-2025.html", title:"KILM", lang:"ID", note:"" },
  { year:2024, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/12/16/d96c70fc6be192f04edf7fe0/indikator-pasar-tenaga-kerja-indonesia-agustus-2024.html", title:"KILM", lang:"ID", note:"" },
  { year:2024, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/06/14/574e2f9c7d3397fbd1754234/indikator-pasar-tenaga-kerja-indonesia-februari-2024.html", title:"KILM", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/12/15/e071c14121358490e96f95cd/indikator-pasar-tenaga-kerja-indonesia-agustus-2023.html", title:"KILM", lang:"ID", note:"" },
  { year:2023, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/06/16/ddcaf3b4a35c8be03f8c7ac5/indikator-pasar-tenaga-kerja-indonesia-februari-2023.html", title:"KILM", lang:"ID", note:"" },
  { year:2022, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2022/12/14/590d81be67bee04024183a0e/indikator-pasar-tenaga-kerja-indonesia-agustus-2022.html", title:"KILM", lang:"ID", note:"" },
  { year:2021, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/12/14/4b80d6ec93429e2d269cbed7/indikator-pasar-tenaga-kerja-indonesia-agustus-2021.html", title:"KILM", lang:"ID", note:"" },
  { year:2021, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/06/15/efb1f5cba486f2ebb0bab891/indikator-pasar-tenaga-kerja-indonesia-februari-2021.html", title:"KILM", lang:"ID", note:"" },
  { year:2020, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/06/26/7b90d91146f0fd8dee4369df/indikator-pasar-tenaga-kerja-indonesia-februari-2020.html", title:"KILM", lang:"ID", note:"" },
  { year:2020, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/12/07/3f3f21ffa24ef6adc7ef2ee8/indikator-pasar-tenaga-kerja-indonesia-agustus-2020.html", title:"KILM", lang:"ID", note:"" },
  { year:2019, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/12/06/25fbc42cac7c24ec0a5e9309/indikator-pasar-tenaga-kerja-indonesia-agustus-2019.html", title:"KILM", lang:"ID", note:"" },
  { year:2019, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/06/14/2647df94a2a708b1976d4383/indikator-pasar-tenaga-kerja-indonesia-februari-2019.html", title:"KILM", lang:"ID", note:"" },
  { year:2018, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/11/30/dbb669d2cf4fad344ffc2577/indikator-pasar-tenaga-kerja-indonesia-agustus-2018.html", title:"KILM", lang:"ID", note:"" },
  { year:2018, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/06/04/f99a09ca269ceb058826ab3e/indikator-pasar-tenaga-kerja-indonesia-februari-2018.html", title:"KILM", lang:"ID", note:"" },
  { year:2017, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/11/30/c49d259986000f2af721403d/indikator-pasar-tenaga-kerja-indonesia-agustus-2017.html", title:"KILM", lang:"ID", note:"" },
  { year:2017, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/08/03/60626049b6ad3a897e96b8c0/indikator-pasar-tenaga-kerja-indonesia-februari-2017.html", title:"KILM", lang:"ID", note:"" },
  { year:2016, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2016/11/30/debfeeb025724bdcb640a11f/indikator-pasar-tenaga-kerja-indonesia-agustus-2016.html", title:"KILM", lang:"ID", note:"" },
  { year:2016, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2016/06/01/a1fac2712da9558efdce9732/indikator-pasar-tenaga-kerja-indonesia-februari-2016.html", title:"KILM", lang:"ID", note:"" },
  { year:2015, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2015/11/30/cfe5ceda105e93adcc20d0d9/indikator-pasar-tenaga-kerja-indonesia-agustus-2015.html", title:"KILM", lang:"ID", note:"" },
  { year:2015, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2015/06/01/8ee95dd5fef0071d28c80f53/indikator-pasar-tenaga-kerja-indonesia-februari-2015.html", title:"KILM", lang:"ID", note:"" },
  { year:2014, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/12/08/40e98aa4c71fc10a6ed89324/indikator-pasar-tenaga-kerja-indonesia-agustus-2014.html", title:"KILM", lang:"ID", note:"" },
  { year:2014, period:"November", category:"Publikasi", link:"", title:"KILM", lang:"ID", note:"tidak ada Sakernas November di 2014" },
  { year:2014, period:"Mei", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/09/08/ee4de7bb7c4536b3d0cb6622/indikator-pasar-tenaga-kerja-indonesia-mei-2014.html", title:"KILM", lang:"ID", note:"" },
  { year:2014, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/05/30/a31a9979047462fe074565a0/indikator-pasar-tenaga-kerja-indonesia-februari-2014.html", title:"KILM", lang:"ID", note:"" },
  { year:2013, period:"November", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/02/25/ddf29617356589286be4fa28/indikator-pasar-tenaga-kerja-indonesia-november-2013.html", title:"KILM", lang:"ID", note:"" },
  { year:2013, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/12/03/600583fab9387bbbb49e2a49/indikator-pasar-tenaga-kerja-indonesia-agustus-2013.html", title:"KILM", lang:"ID", note:"" },
  { year:2013, period:"Mei", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/08/30/b0595a5f650aaf7770b04d85/indikator-pasar-tenaga-kerja-indonesia-mei-2013.html", title:"KILM", lang:"ID", note:"" },
  { year:2013, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/05/31/2f017b72135b32f45e513e4c/indikator-pasar-tenaga-kerja-indonesia-februari-2013.html", title:"KILM", lang:"ID", note:"" },
  { year:2012, period:"November", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/02/28/0ae1550d384d196f20507cf2/indikator-pasar-tenaga-kerja-indonesia-november-2012.html", title:"KILM", lang:"ID", note:"" },
  { year:2012, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2012/11/30/92622e8053bca31af915c309/indikator-pasar-tenaga-kerja-indonesia-agustus-2012.html", title:"KILM", lang:"ID", note:"" },
  { year:2012, period:"Mei", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2012/09/05/f303188c7b2f3bb237f1f77f/indikator-pasar-tenaga-kerja-indonesia-mei-2012.html", title:"KILM", lang:"ID", note:"" },
  { year:2012, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2012/06/04/ce7ca2c4e8ac6b59c3dc1f37/indikator-pasar-tenaga-kerja-indonesia-februari-2012.html", title:"KILM", lang:"ID", note:"" },
  { year:2011, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2011/11/28/015e5c528cd28e48eb6746de/indikator-pasar-tenaga-kerja-indonesia-agustus-2011.html", title:"KILM", lang:"ID", note:"" },
  { year:2011, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2011/07/29/0ebbab182191c0a81920d19e/indikator-pasar-tenaga-kerja-indonesia-februari-2011.html", title:"KILM", lang:"ID", note:"pertama kali diterbitkan" },
  { year:2000, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/1hr_wueqTWoN-3n2b5kyu9RAPSDHyXIDh/preview", title:"Kode KBLI 2000", lang:"ID", note:"" },
  { year:2005, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/1nfgELonhGXOygDPWe_EJ7ULuxoK3yD4B/preview", title:"Kode KBLI 2005", lang:"ID", note:"" },
  { year:2009, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/1zXYx9jqOweicyDWi3fC0YTJ75vNkjZM0/preview", title:"Kode KBLI 2009", lang:"ID", note:"" },
  { year:1982, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/1hr_wueqTWoN-3n2b5kyu9RAPSDHyXIDh/preview", title:"Kode KJI 1982", lang:"ID", note:"" },
  { year:1994, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/147QvWKzSV-LlUD-aCWa9TYqAfm6boYzrCoJ8y0y4xZY/preview", title:"Kode Sektor 1986-1994", lang:"ID", note:"berlaku di 1986-1994" },
  { year:1993, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/147QvWKzSV-LlUD-aCWa9TYqAfm6boYzrCoJ8y0y4xZY/preview", title:"Kode Sektor 1986-1994", lang:"ID", note:"berlaku di 1986-1994" },
  { year:1992, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/147QvWKzSV-LlUD-aCWa9TYqAfm6boYzrCoJ8y0y4xZY/preview", title:"Kode Sektor 1986-1994", lang:"ID", note:"berlaku di 1986-1994" },
  { year:1991, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/147QvWKzSV-LlUD-aCWa9TYqAfm6boYzrCoJ8y0y4xZY/preview", title:"Kode Sektor 1986-1994", lang:"ID", note:"berlaku di 1986-1994" },
  { year:1990, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/147QvWKzSV-LlUD-aCWa9TYqAfm6boYzrCoJ8y0y4xZY/preview", title:"Kode Sektor 1986-1994", lang:"ID", note:"berlaku di 1986-1994" },
  { year:1989, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/147QvWKzSV-LlUD-aCWa9TYqAfm6boYzrCoJ8y0y4xZY/preview", title:"Kode Sektor 1986-1994", lang:"ID", note:"berlaku di 1986-1994" },
  { year:1988, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/147QvWKzSV-LlUD-aCWa9TYqAfm6boYzrCoJ8y0y4xZY/preview", title:"Kode Sektor 1986-1994", lang:"ID", note:"berlaku di 1986-1994" },
  { year:1987, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/147QvWKzSV-LlUD-aCWa9TYqAfm6boYzrCoJ8y0y4xZY/preview", title:"Kode Sektor 1986-1994", lang:"ID", note:"berlaku di 1986-1994" },
  { year:1986, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/147QvWKzSV-LlUD-aCWa9TYqAfm6boYzrCoJ8y0y4xZY/preview", title:"Kode Sektor 1986-1994", lang:"ID", note:"berlaku di 1986-1994" },
  { year:1996, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/1ev5rW7nMKO1Thj7xqHLX8NRyQcZYXx1i/preview", title:"Kode Sektor 1996-1999", lang:"ID", note:"" },
  { year:1997, period:"-", category:"Klasifikasi", link:"https://drive.google.com/file/d/1O-ENWaqqijPBI4aVnn5_Id521N9G6cw4/preview", title:"Kode Sektor 1997", lang:"ID", note:"" },
  { year:2026, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1XFb7u_S4xHiKJMx4FFFsRqy5tFD8M6kn/view?usp=sharing", title:"Kuesioner", lang:"ID", note:"" },
  { year:2025, period:"November", category:"Kuesioner", link:"https://drive.google.com/file/d/1NE0BzLG9mF_xHzhplyfYeWvuzlFNN-SR/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2025, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1SxeXN8bG-9EBwW-CklnoEcUyZPHfbUZB/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2025, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/144Jn0sTv4OKUv2j9Oh51fY1W4s_bOMUN/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2024, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1fVI32P5as6jmszrkKEjHmadu9LGXG1NU/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2024, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1n7XXbGnTDGCmah0NM0k7ILIzEy1joXM9/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2023, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1Zkqhm9rm1Xyn4PuknYnhWBLHt_8N4OeO/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1eEeglx_SBJxg3_zs7nyJo9iGrjNcWjoU/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2022, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1BuHprM2NxEYFnhdhuD8eWHJ7UMP6J820/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2022, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1ZZa8286OMRAgnKr85mHwjSKtqMWBUtUC/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2021, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1v3CcJDlwePL-b5WuZur4q3hkuUALxZlb/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2021, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1ajPf3dy3EOgmpoRxdjy0iLsGFEzg96N7/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2020, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/12YtOpVRgoAw7Ca99IXL0dhcB_NDeZH5r/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2020, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1uopRLxDlg161u4cvaiX8SmDryY8J-ELv/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2019, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1z01GGgbYZxodheoWxb_LSyRXuzuNC-fk/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2019, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1plo1IRT6WeG3Hs8l-aBjasvFdlSQj4_4/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2018, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1ePwRxz19DOlwuXJwncJOcDv5Xc-PwvSl/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2018, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/11jo21tnO3dto2jxKCezsWCgJKtFsWJyB/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2017, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/17Flq9cunsaIvRqvVG4m7kR9e3LadVD42/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2017, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1yez4L864XGNvfDueFqnRTDT7GIv1Hv9K/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2016, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1uR0cw3imxmbs-PF9UH1sZz0lNXQiN6YU/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2016, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1VO1ez6shkuPUwtm907Yp4gSANes-vcFC/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2015, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1hktoyHoeTQwnK6OmpePnieelQ7emWu40/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2015, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1swM3rAmfD3XLOvSyR-I4gZP2yhRgPA6K/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2014, period:"Mei", category:"Kuesioner", link:"https://drive.google.com/file/d/1N65Qrdv5ewob1SDlo--zI-jJ8WMTMiuD/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2014, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1oVQQDrRSYtt6vFBZF0vDULAAQpBI5Pbi/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2014, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/10PP5preJgx0yZwVxxanLpa9lbO408G5y/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2013, period:"November", category:"Kuesioner", link:"https://drive.google.com/file/d/1xWJsC3ZSI2zUHPT6RVxqD-vGmGjBTTWS/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2013, period:"Mei", category:"Kuesioner", link:"https://drive.google.com/file/d/1TVa7Hy_9soVaON57m_iSzBRf7IvsBF9I/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2013, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1OfIpaunafoSZ7DjKuotzLr0aDq3T0F7F/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2013, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/109r_2wmO6SVWFyK7Dzm2RihmqJ-o0HdN/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2012, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1rdDDNGkQF04DCGVpmgjL5EiUcGJAlNTz/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2011, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1m6BD1oL8IQTY4URW8UDNoQe4lZqentfQ/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2010, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1B5HyiQJNCmJpRVl7OxLfIgknUy9bpuRg/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2009, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/164RCkEaxHKSFaLUHfPiNThfLgd_qft_b/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2008, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1rOR5Iz1DGNSxBsXjJur1Vk_fqF0dO0T9/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2007, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1XcAvg4RtjRNxZWxW9VMy6vqjIBNlhqjr/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2006, period:"November", category:"Kuesioner", link:"https://drive.google.com/file/d/1lQXq9n9s4KuC12ozFIxlwPNLJ9g0uv2I/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2006, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1hRC9gna3RHbHBhbC0-6VDbb2ULmeitNX/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2005, period:"Februari", category:"Kuesioner", link:"https://drive.google.com/file/d/1UcLbc8khF9rTzsnMmz2eEj9ux0Hp8Az-/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2005, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1tQ3Kwsfz-MkmqnrrWS0vFmurwrgRGLA3/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2004, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1bemkW8Ce5mIfxpCZtymvUXcTMQiW-VjF/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2003, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1WBJmzpneIwA0tv_A5zVKfVI7S2KonIJ4/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2002, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1WcESB4bGA4hyElmzCx6oHuT_AMBNY-qu/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2001, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1R97gpVGxqaAWaqqZMUrQoKrYJvVJaW1m/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2000, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/19hN-0y6YUcZPM-UPa37ySgYsvW2mXYeU/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:1999, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1WPLYk8U85zQJVhWMAz7OWDZLQXwC5S5w/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:1998, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1DDtADqhAY8Jcb2PWWY8lKUW14KqSxfiw/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:1997, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/19RFSQglY5QQ1OZVRubyWwV3UF4L8jmcq/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:1996, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1NLN6CXuxxrFib1GZc7revEg17TOTsYEk/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:1993, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/10p9l6O1dyXUORjLvijSvmmLnRPfgc9SU/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:1990, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1Ne7MluH3d_clSGKf0ctHKmGI6U1vFbYH/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:1989, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/153Nvz10ieMa1a0zrPddmPIFhAwYLtO1C/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:1987, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1iJ-yQXoX2QJ_KySzeyepU8d5vwYW6kOr/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:1986, period:"Agustus", category:"Kuesioner", link:"https://drive.google.com/file/d/1BUM5J9BgdSSMHKKBsOX038qoPayqQiCy/preview", title:"Kuesioner", lang:"ID", note:"" },
  { year:2026, period:"Februari", category:"Pedoman", link:"https://drive.google.com/file/d/1wEF2LgGQifQaVCZl_QGRCwrjn37oh5ZC/preview", title:"Pencacahan", lang:"ID", note:"" },
  { year:2026, period:"Februari", category:"Pedoman", link:"https://drive.google.com/file/d/1c1ksdyo_0oqRcZjoghYhpUzBbOR-2aj8/preview", title:"Pemeriksaan", lang:"ID", note:"" },
  { year:2026, period:"Februari", category:"Pedoman", link:"https://drive.google.com/file/d/1Js810JNBBQcfqUOS_RSI6vOMkAQTjmHD/preview", title:"Teknis", lang:"ID", note:"" },
  { year:2025, period:"Agustus", category:"Pedoman", link:"", title:"Pemeriksaan", lang:"ID", note:"" },
  { year:2025, period:"Agustus", category:"Pedoman", link:"", title:"Teknis", lang:"ID", note:"" },
  { year:2025, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2025, period:"Agustus", category:"Klasifikasi", link:"https://drive.google.com/file/d/1PwsNDauaB8op59dRIx1zs6HQP797EJLg/preview", title:"Buku Kode", lang:"ID", note:"KBLI KBJI Pendidikan Pelatihan Negara" },
  { year:2025, period:"Februari", category:"Pedoman", link:"", title:"Pemeriksaan", lang:"ID", note:"" },
  { year:2025, period:"Februari", category:"Pedoman", link:"", title:"Teknis", lang:"ID", note:"" },
  { year:2025, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2025, period:"Februari", category:"Klasifikasi", link:"https://drive.google.com/file/d/13-CXof2uy1CEImeMbszBOvwiLx6pu6DJ/preview", title:"Buku Kode", lang:"ID", note:"KBLI KBJI Pendidikan Pelatihan Negara" },
  { year:2024, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2024, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2024, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2024, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2023, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2023, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2022, period:"Agustus", category:"Pedoman", link:"https://drive.google.com/file/d/10r13KjcclH-NVuLvCtmbajZXCvludr4g/preview", title:"Pencacahan", lang:"ID", note:"" },
  { year:1994, period:"July", category:"Kuesioner", link:"https://drive.google.com/file/d/10mVEQGNw27oJKSQwYnIqI0OSa6V2rbUV/preview", title:"Kuesioner July V1 (ID)", lang:"ID", note:"" },
  { year:1994, period:"July", category:"Kuesioner", link:"https://drive.google.com/file/d/1TKu_rP2K0LgvUY8CgGMA2Do5V3ZOqh79/preview", title:"Kuesioner July V2 (ID)", lang:"ID", note:"" },
  { year:2007, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2008/12/07/223d40cf899480c5a88f81e3/statistik-penduduk-lanjut-usia-2007.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"pertama kali memakai Sakernas" },
  { year:2008, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2009/11/09/34483a9659ef905e7a8e6dda/statistik-penduduk-lanjut-usia-2008.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2009, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2010/11/25/03cc9539a716e6fc95b49437/statistik-penduduk-lanjut-usia-2009.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2010, period:"Agustus", category:"Publikasi", link:"", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"tidak terbit" },
  { year:2011, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2012/11/07/847c93e911c981fabc5c0b59/statistik-penduduk-lanjut-usia-indonesia-2011.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2012, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/09/25/82a8f419220eb638d9dbb297/statistik-penduduk-lanjut-usia-2012.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2013, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/10/29/fd6f0a25a079f8b00a8f06a2/statistik-penduduk-lanjut-usia-2013.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2014, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2015/11/02/e8375b9b7a8e0d380a1fd1da/statistik-penduduk-lanjut-usia-2014.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2015, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2016/11/07/f9d00ad72285396ecb1801dc/statistik-penduduk-lanjut-usia-2015.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2016, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/11/17/107752aa20f3f8cb08d9dabe/statistik-penduduk-lanjut-usia-2016.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2017, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/04/13/7a130a22aa29cc8219c5d153/statistik-penduduk-lanjut-usia-2017.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2018, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/12/21/eadbab6507c06294b74adf71/statistik-penduduk-lanjut-usia-2018.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2019, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/12/20/ab17e75dbe630e05110ae53b/statistik-penduduk-lanjut-usia-2019.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2020, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/12/21/0fc023221965624a644c1111/statistik-penduduk-lanjut-usia-2020.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2021, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/12/21/c3fd9f27372f6ddcf7462006/statistik-penduduk-lanjut-usia-2021.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2022, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2022/12/27/3752f1d1d9b41aa69be4c65c/statistik-penduduk-lanjut-usia-2022.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/12/29/5d308763ac29278dd5860fad/statistik-penduduk-lanjut-usia-2023.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2024, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/12/31/a00d4477490caaf0716b711d/statistik-penduduk-lanjut-usia-2024.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2025, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/12/12/868d335b088dcddc3ddee052/statistik-penduduk-lanjut-usia-2025.html", title:"Statistik Penduduk Lanjut Usia", lang:"ID", note:"" },
  { year:2009, period:"Agustus", category:"Klasifikasi", link:"https://www.bps.go.id/id/publication/2010/11/22/94df7552c75f65e4585b098e/statistik-mobilitas-penduduk-dan-tenaga-kerja-2010.html", title:"Statistik Mobilitas Penduduk dan Tenaga Kerja", lang:"ID", note:"" },
  { year:2012, period:"Agustus", category:"Klasifikasi", link:"https://www.bps.go.id/id/publication/2013/11/04/64737701c16b3d13919ac1e0/statistik-mobilitas-penduduk-dan-tenaga-kerja-2013.html", title:"Statistik Mobilitas Penduduk dan Tenaga Kerja", lang:"ID", note:"" },
  { year:2016, period:"Agustus", category:"Klasifikasi", link:"https://www.bps.go.id/id/publication/2017/12/25/2017000000000000102366/statistik-mobilitas-penduduk-dan-tenaga-kerja-2017.html", title:"Statistik Mobilitas Penduduk dan Tenaga Kerja", lang:"ID", note:"" },
  { year:2018, period:"Agustus", category:"Klasifikasi", link:"https://www.bps.go.id/id/publication/2019/12/04/4e56f5c350dda045f875f66c/statistik-mobilitas-penduduk-dan-tenaga-kerja-2019.html", title:"Statistik Mobilitas Penduduk dan Tenaga Kerja", lang:"ID", note:"" },
  { year:2020, period:"Agustus", category:"Klasifikasi", link:"https://www.bps.go.id/id/publication/2021/12/21/a15176a0d458bc8f297d3ee7/statistik-mobilitas-penduduk-dan-tenaga-kerja-2021.html", title:"Statistik Mobilitas Penduduk dan Tenaga Kerja", lang:"ID", note:"" },
  { year:2022, period:"Agustus", category:"Klasifikasi", link:"https://www.bps.go.id/id/publication/2023/12/22/82a2bd337ba802ac19611b71/statistik-mobilitas-penduduk-dan-tenaga-kerja-2023.html", title:"Statistik Mobilitas Penduduk dan Tenaga Kerja", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Klasifikasi", link:"https://www.bps.go.id/id/publication/2024/12/13/8264549bd1ccfccb993c3528/statistik-mobilitas-penduduk-dan-tenaga-kerja-2023-2024.html", title:"Statistik Mobilitas Penduduk dan Tenaga Kerja", lang:"ID", note:"" },
  { year:2024, period:"Agustus", category:"Klasifikasi", link:"https://www.bps.go.id/id/publication/2025/12/31/7c6b5b2ab96788c258cad7f6/statistik-mobilitas-penduduk-dan-tenaga-kerja-2024.html", title:"Statistik Mobilitas Penduduk dan Tenaga Kerja", lang:"ID", note:"" },
  { year:2022, period:"Februari", category:"Pedoman", link:"https://drive.google.com/file/d/1zKgKU_3SGBhzXi32qltyIww9-KL542-4/preview", title:"Pengawasan", lang:"ID", note:"" },
  { year:2022, period:"Februari", category:"Pedoman", link:"https://drive.google.com/file/d/1HRWs4bwJSuJLxSp4DFmhPu9DKf3cMyLn/preview", title:"Pencacahan", lang:"ID", note:"" },
  { year:2022, period:"Agustus", category:"Pedoman", link:"https://drive.google.com/file/d/1LvW18nGErcNfKFLynDh3OnqF61dpe3eJ/preview", title:"Pengawasan", lang:"ID", note:"" },
  { year:2021, period:"Agustus", category:"Pedoman", link:"https://drive.google.com/file/d/1PUk0wtNfSrWHZVc8KJZBCJUssyxqHW0C/preview", title:"Pencacahan", lang:"ID", note:"" },
  { year:2021, period:"Februari", category:"Pedoman", link:"https://drive.google.com/file/d/1foxww7NPhPKzJIoS1rQe-7Qb-V-25Anr/preview", title:"Pengawasan", lang:"ID", note:"" },
  { year:2021, period:"Februari", category:"Pedoman", link:"https://drive.google.com/file/d/1NIKkvrau3Ga5iozmgakK73tuUg6azkpq/preview", title:"Pencacahan", lang:"ID", note:"" },
  { year:2021, period:"Agustus", category:"Pedoman", link:"https://drive.google.com/file/d/1-X8D8Dq72z5LJPZ5mg2JWZAPSwSj1SBh/preview", title:"Pengawasan", lang:"ID", note:"" },
  { year:2020, period:"Agustus", category:"Pedoman", link:"https://drive.google.com/file/d/16eZcL79oliUpVsZnUUJywO5kRaoN7wvU/preview", title:"Pencacahan", lang:"ID", note:"" },
  { year:2020, period:"Februari", category:"Pedoman", link:"https://drive.google.com/file/d/1oz6pdfzFyFJKPb1KhAo7YXKzdpXLiTDh/preview", title:"Pengawasan", lang:"ID", note:"" },
  { year:2020, period:"Februari", category:"Pedoman", link:"https://drive.google.com/file/d/1l5lY-Zh7QB2EB9NQ0VV_Soc9Kgp_JJEV/preview", title:"Pencacahan", lang:"ID", note:"" },
  { year:2020, period:"Agustus", category:"Pedoman", link:"https://drive.google.com/file/d/1VLj2GG6D3o_c_8Ddlrw1jbEKLM3vw8SG/preview", title:"Pengawasan", lang:"ID", note:"" },
  { year:2019, period:"Agustus", category:"Pedoman", link:"https://drive.google.com/file/d/1B2ZOAzVTn-vEt_35w2rzXqbWClntMgsJ/preview", title:"Pencacahan", lang:"ID", note:"" },
  { year:2019, period:"Februari", category:"Pedoman", link:"https://drive.google.com/file/d/1n1OUDgIyWWShxPOVWynG5lVx0cQgsoi8/preview", title:"Pengawasan", lang:"ID", note:"" },
  { year:2019, period:"Februari", category:"Pedoman", link:"https://drive.google.com/file/d/1zEY-iLYNZ9qUnk5_WZ2wxI_wRWN_yc4G/preview", title:"Pencacahan", lang:"ID", note:"" },
  { year:2019, period:"Agustus", category:"Pedoman", link:"https://drive.google.com/file/d/1akWBtwF2CX9BoQoxjuGu_B_jAOz9RwiA/preview", title:"Pengawasan", lang:"ID", note:"" },
  { year:2018, period:"Agustus", category:"Pedoman", link:"https://drive.google.com/file/d/1gXmbSfbWdxtV0z9Ntg7zJgmlHcS5lZ0M/preview", title:"Pencacahan", lang:"ID", note:"" },
  { year:2018, period:"Agustus", category:"Pedoman", link:"https://drive.google.com/file/d/17VWA_jN7iMEE5olI1_kwsnDueP6gyNcB/preview", title:"Pengawasan", lang:"ID", note:"" },
  { year:2017, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2017, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2017, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2017, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2016, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2016, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2016, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2016, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2015, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2015, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2015, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2015, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2014, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2014, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2014, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2014, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2013, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2013, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2013, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2013, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2012, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2012, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2012, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2012, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2011, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2011, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2011, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2011, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2010, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2010, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2010, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2010, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2009, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2009, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2009, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2009, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2008, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2008, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2008, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2008, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2007, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2007, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2007, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2007, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2006, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2006, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2006, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2006, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2005, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2005, period:"November", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2005, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2005, period:"November", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2004, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2004, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2004, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2004, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2003, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2003, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2003, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2003, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2002, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2002, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2002, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2002, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2001, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2001, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2001, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2001, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2000, period:"Agustus", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2000, period:"Februari", category:"Pedoman", link:"", title:"Pencacahan", lang:"ID", note:"" },
  { year:2000, period:"Februari", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2000, period:"Agustus", category:"Pedoman", link:"", title:"Pengawasan", lang:"ID", note:"" },
  { year:2009, period:"August", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2010/01/26/16e071626b6d67e4fd413019/pekerja-anak-di-indonesia-2009.html", title:"Pekerja Anak", lang:"ID", note:"" },
  { year:2005, period:"Mei", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2005/05/15/f812e5a1ffcfc0d090120d7f/statistik-pekerja-anak-2005.html", title:"Pekerja Anak", lang:"ID", note:"Pilot Studi, bukan data Sakernas" },
  { year:2023, period:"Januari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/01/24/26f9953aa34944a5ad539815/booklet-pekerja-anak-di-indonesia-2022-sebelum-dan-semasa-pandemi-covid-19-.html", title:"Pekerja Anak", lang:"ID", note:"Booklet Pekerja Anak di Indonesia 2022 Sebelum dan Semasa Pandemi COVID-19." },
  { year:1987, period:"-", category:"Sejarah", link:"https://drive.google.com/file/d/1zkGqLaJDk3Z1NmV9JMQEUcQ8h7RZDRAz/preview", title:"Sakernas Volume 1", lang:"ID", note:"Developmet Studies Volume I Labor Force and Wages Bappenas BPS" },
  { year:1988, period:"-", category:"Sejarah", link:"https://drive.google.com/file/d/1jTZK25BGtjVtRQwffXiFPHy79t7wiKqN/preview", title:"Sakernas Volume 2", lang:"ID", note:"Developmet Studies Volume II Wage Data Bappenas BPS" },
  { year:"-", period:"-", category:"Sejarah", link:"https://dsbb.imf.org/sdds/summary-methodology-base/country/IDN/category/EMP00", title:"Sejarah", lang:"EN", note:"metadata IMF" },
  { year:"-", period:"-", category:"Sejarah", link:"https://www.rand.org/health/surveys/bps/sakernas.html", title:"Sejarah", lang:"EN", note:"metadata RAND" },
  { year:2006, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2006/05/15/a6be87beacd9859e91c2bf2e/statistik-pengangguran-2001-2006.html", title:"Statistik Pengangguran", lang:"ID", note:"" },
  { year:2026, period:"Februari", category:"Klasifikasi", link:"https://drive.google.com/file/d/19Qaxu5mz2yvO90qunKj1_iY3RLTbUjg8/preview", title:"Buku Kode", lang:"ID", note:"KBLI KBJI Pendidikan Pelatihan Negara" },
  { year:2025, period:"November", category:"Klasifikasi", link:"https://drive.google.com/file/d/1HuHCUknjikeBCpZqoSw4eefGTg43yhM-/PREVIEW", title:"", lang:"ID", note:"" },
  { year:2025, period:"November", category:"Pedoman", link:"https://drive.google.com/file/d/17d4edsB1ClocKZtFY2y7yOYSso5oDs6Z/preview", title:"Pemeriksaan", lang:"ID", note:"" },
  { year:2025, period:"November", category:"Pedoman", link:"https://drive.google.com/file/d/1wmZMlcyEm3sB_WtRcxYoJEEUyW-oiHMK/preview", title:"Teknis", lang:"ID", note:"" },
  { year:2025, period:"November", category:"Pedoman", link:"https://drive.google.com/file/d/1c_bq7IJA2L6hoNjJBURR4Il2OTmNYk3J/preview", title:"Pencacahan", lang:"ID", note:"" },
  { year:2024, period:"Februari", category:"Klasifikasi", link:"https://drive.google.com/file/d/1u2-wimEOpKOt5M3uMIt6d_vNI4qEXg0h/preview", title:"Buku Kode", lang:"ID", note:"KBLI KBJI Pendidikan Pelatihan Negara" },
  { year:2024, period:"Agustus", category:"Klasifikasi", link:"https://drive.google.com/file/d/18422Km_r6d4_NHHpS28r7EE-RCTH7LfA/preview", title:"Buku Kode", lang:"ID", note:"KBLI KBJI Pendidikan Pelatihan Negara" },
  { year:2023, period:"Februari", category:"Klasifikasi", link:"https://drive.google.com/file/d/19afysK9iroFCNexmUi5HH2mcCgfJF8UO/preview", title:"Buku Kode", lang:"ID", note:"KBLI KBJI Pendidikan Pelatihan Negara" },
  { year:2023, period:"Agustus", category:"Klasifikasi", link:"https://drive.google.com/file/d/1QyE438dOXITCeVIGrFRdWILsIEzX5PdE/preview", title:"Buku Kode", lang:"ID", note:"KBLI KBJI Pendidikan Pelatihan Negara" },
  { year:2022, period:"Februari", category:"Klasifikasi", link:"https://drive.google.com/file/d/15Z0XbaGDK9PfUerf3tuFHRh8_Hf9SMIg/preview", title:"Buku Kode", lang:"ID", note:"KBLI KBJI Pendidikan Pelatihan Negara" },
  { year:2022, period:"Agustus", category:"Klasifikasi", link:"https://drive.google.com/file/d/1C55dH90VxPsXfLOFtwVijl9UI3__FHjD/preview", title:"Buku Kode", lang:"ID", note:"KBLI KBJI Pendidikan Pelatihan Negara" },
  { year:2021, period:"Februari", category:"Klasifikasi", link:"https://drive.google.com/file/d/1eVfLj7uz4Pftj_N2Hqd1oBmAwsN-tddE/preview", title:"Buku Kode", lang:"ID", note:"KBLI KBJI Pendidikan Pelatihan Negara" },
  { year:2021, period:"Agustus", category:"Klasifikasi", link:"https://drive.google.com/file/d/1xHHIPLLhemiShsGvpSs57u7FGH1RWkIM/preview", title:"Buku Kode", lang:"ID", note:"KBLI KBJI Pendidikan Pelatihan Negara" },
  { year:2020, period:"Agustus", category:"Klasifikasi", link:"https://drive.google.com/file/d/12bDq6cnkcKr7Pl6QY2oDIRr0bBRAzIQ1/preview", title:"Buku Kode", lang:"ID", note:"KBLI KBJI Pendidikan Pelatihan Negara" },
  { year:2024, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/04/28/1ecc9dec1ef7a591babf5962/indikator-pekerjaan-layak-di-indonesia-2024.html", title:"Pekerjaan Layak", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/04/30/8fe6c4f34d5f1b9953903873/indikator-pekerjaan-layak-di-indonesia-2023.html", title:"Pekerjaan Layak", lang:"ID", note:"" },
  { year:2022, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/04/17/65695a2b5a039c58071d23b6/indikator-pekerjaan-layak-di-indonesia-2022.html", title:"Pekerjaan Layak", lang:"ID", note:"" },
  { year:2021, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2022/04/08/1ea92e310421c90fcc82a84e/indikator-pekerjaan-layak-di-indonesia-2021.html", title:"Pekerjaan Layak", lang:"ID", note:"" },
  { year:2020, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/07/06/a150047cc0de89dd9fafa881/indikator-pekerjaan-layak-di-indonesia-2020.html", title:"Pekerjaan Layak", lang:"ID", note:"" },
  { year:2019, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/06/19/893d294190427e5eace18cd6/indikator-pekerjaan-layak-di-indonesia-2019.html", title:"Pekerjaan Layak", lang:"ID", note:"" },
  { year:2018, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/07/19/49ca683c8f1917851b094468/indikator-pekerjaan-layak-di-indonesia-2018.html", title:"Pekerjaan Layak", lang:"ID", note:"" },
  { year:2017, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/09/28/5a2eae80bd3bb6b57d9eb726/indikator-pekerjaan-layak-di-indonesia-2017.html", title:"Pekerjaan Layak", lang:"ID", note:"pertama kali diterbitkan" },
  { year:2020, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/12/21/4a39564b84a1c4e7a615f28b/statistik-pemuda-indonesia-2020.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2021, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/12/21/52333d2ce0a748fff6469811/statistik-pemuda-indonesia-2021.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2018, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/12/21/572f941511d090083dd742d6/statistik-pemuda-indonesia-2018.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2019, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/12/20/8250138f59ccebff3fed326a/statistik-pemuda-indonesia-2019.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2022, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2022/12/27/6791d20b0b4cadae9de70a4d/statistik-pemuda-indonesia-2022.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/12/29/18781f394974f2cae5241318/statistik-pemuda-indonesia-2023.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2024, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/12/31/b2dbaac4542352cea8794590/statistik-pemuda-indonesia-2024.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2025, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/12/12/1a88777089ce471db17bb1fb/statistik-pemuda-indonesia-2025.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2017, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/04/13/040941963dd0c2fe89ffcee6/statistik-pemuda-indonesia-2017.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2016, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/11/03/5cdcfabd0f6fca476cb548e6/statistik-pemuda-indonesia-2016.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2015, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2016/11/07/18b4ab7c9fd607512cd44d02/statistik-pemuda-indonesia-2015.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2014, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2015/11/02/f4bbb65bbc11ad61a75695b3/statistik-pemuda-indonesia-2014.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2013, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/10/29/d33a26194b59dee09f04d253/statistik-pemuda-indonesia-2013.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2012, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/10/25/0e82db52511c379333382845/statistik-pemuda-indonesia-2012.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2011, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2012/11/07/57d48a369d388782ae7d3573/statistik-pemuda-indonesia-2011.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2009, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2010/10/25/e3e90f553027092d1874f1e6/statistik-pemuda-indonesia-2009.html", title:"Statistik Pemuda", lang:"ID", note:"" },
  { year:2008, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2009/11/09/0c34a5e6b7c10969661517f2/statistik-pemuda-indonesia-2008.html", title:"Statistik Pemuda", lang:"ID", note:"pertama kali memakai Sakernas" },
  { year:2005, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2005/05/15/414a6c254f50c7f6be8cae33/keadaan-pekerja-buruh-karyawan-di-indonesia-februari-2005.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2005, period:"November", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2005/05/15/776c9fbcf8a2b21e2f2099cb/keadaan-pekerja-buruh-karyawan-di-indonesia-november-2005.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2006, period:"Februari", category:"Publikasi", link:"", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2006, period:"Agustus", category:"Publikasi", link:"", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2007, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2007/05/15/3bc280b9fd93d577d32e714b/keadaan-pekerja-di-indonesia-februari-2007.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2007, period:"Agustus", category:"Publikasi", link:"", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2008, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2008/05/15/faef6c07d04950da5833de8f/keadaan-pekerja-di-indonesia-februari-2008.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2008, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2009/01/27/ca9e29a2cf16aaa237ee725f/keadaan-pekerja-di-indonesia-agustus-2008.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2009, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2009/05/15/5c67a9a948f56c022f7605c0/keadaan-pekerja-di-indonesia-februari-2009.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2009, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2010/07/07/bfb6dd254217ae988ae2e463/keadaan-pekerja-di-indonesia-agustus-2009.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2010, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2010/06/02/d5adad41b69936de4767951d/keadaan-pekerja-di-indonesia-februari-2010.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2010, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2011/01/17/c7781002004aa2a559cab7f5/keadaan-pekerja-di-indonesia-agustus-2010.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2011, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2012/02/15/bc7151bdb4d5d91f66726e94/keadaan-pekerja-di-indonesia-februari-2011.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2011, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2011/11/28/ff4efcb39318dd230da3a838/keadaan-pekerja-di-indonesia-agustus-2011.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2012, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2012/06/06/d58fe12692cabef0b2d5cfd5/keadaan-pekerja-di-indonesia-februari-2012.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2012, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2012/11/30/61906482dfd1cad64c840fc9/keadaan-pekerja-di-indonesia-agustus-2012.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2013, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/05/31/81d288f1825eb1b64671b525/keadaan-pekerja-di-indonesia-februari-2013.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2013, period:"Mei", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/08/30/0f285d1c2e188bc2dcc646e9/keadaan-pekerja-di-indonesia-mei-2013.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2013, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2013/11/29/b443315b3aee8754f4c34bb1/keadaan-pekerja-di-indonesia-agustus-2013.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2013, period:"November", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/02/25/faee923f186a5cd41d94aeac/keadaan-pekerja-di-indonesia-november-2013.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2014, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/05/30/80ea203a5e0de25b8f1ef669/keadaan-pekerja-di-indonesia-februari-2014.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2014, period:"Mei", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/09/08/01baee9ac483b0bc88142473/keadaan-pekerja-di-indonesia-mei-2014.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2014, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/11/28/73d46d6a0c2c21b73a6e5b12/keadaan-pekerja-di-indonesia-agustus-2014.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2015, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2015/06/01/789dc46ae3cb84d7fe4b5171/keadaan-pekerja-di-indonesia-februari-2015.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2015, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2015/11/30/f8bdb3fd36c8f9c45722b361/keadaan-pekerja-di-indonesia-agustus-2015.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2016, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2016/06/01/fab9dc085ed2bb9b1b866ec7/keadaan-pekerja-di-indonesia-februari-2016.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2016, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2016/11/30/bb28649fda402e4b0c346fba/keadaan-pekerja-di-indonesia-agustus-2016.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2017, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/08/03/184dafb04f72b286f8f16e02/keadaan-pekerja-di-indonesia-februari-2017.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2017, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/11/30/70ab657f1869564f63b7bcfc/keadaan-pekerja-di-indonesia-agustus-2017.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2018, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/06/04/ffb632ad65f770914900ac29/keadaan-pekerja-di-indonesia-februari-2018.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2018, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/11/30/de7c87ed6a6ec2513667033e/keadaan-pekerja-di-indonesia-agustus-2018.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2019, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/05/31/4a6b3b44a64b3250c10f2d36/keadaan-pekerja-di-indonesia-februari-2019.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2019, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/11/29/c21630ee39b9004459680923/keadaan-pekerja-di-indonesia-agustus-2019.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2020, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/06/19/43f6d15bcc31f4170a89e571/keadaan-pekerja-di-indonesia-februari-2020.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2020, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/11/30/351ae49ac1ea9d5f2e42c0da/keadaan-pekerja-di-indonesia-agustus-2020.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2021, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/06/08/ccf5b352d7f42b9718b93f44/keadaan-pekerja-di-indonesia-februari-2021.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2021, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/12/07/cad6895cc9045d3053295be9/keadaan-pekerja-di-indonesia-agustus-2021.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2022, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2022/06/07/76fb4f0b11d3fc22f135a178/keadaan-pekerja-di-indonesia-februari-2022-.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2022, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2022/12/07/2b8168cecb67a77ab7a6857d/keadaan-pekerja-di-indonesia-agustus-2022.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2013, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2014/11/03/6e30dae6c26ab9d1db1189a1/statistik-pendapatan-2013.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2014, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2015/10/02/f84a60239ee2ca9365120690/statistik-pendapatan-2014.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2016, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/01/25/2311dc4ce5df90adc95b53b1/statistik-pendapatan-agustus-2016.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2016, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/01/25/d3247fbbbea5a1eebbf603be/statistik-pendapatan-februari-2016.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2017, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/08/03/9afb3c2bfd48accc4e52eb40/statistik-pendapatan-februari-2017.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2017, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2017/11/30/87f1f9e92d0b7efe0eb06183/statistik-pendapatan-agustus-2017.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2018, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/06/04/769946b424c9a22b0732c3e5/statistik-pendapatan-februari-2018.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2018, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2018/11/30/c09766cb5f15e934d24893a7/statistik-pendapatan-agustus-2018.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2019, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/05/31/4f7829e7743f9dfbd498577e/statistik-pendapatan-februari-2019.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2019, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2019/11/29/f8c56e88694f87761879e9bf/statistik-pendapatan-agustus-2019.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2020, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/06/19/0dce3c66158f35e8ab006612/statistik-pendapatan-februari-2020.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2020, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2020/11/30/014df9d4f339441b23f8751a/statistik-pendapatan-agustus-2020.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2021, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/06/08/a1191be5df6884f9baf32aa2/statistik-pendapatan-februari-2021.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2021, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2021/12/07/bb7172d826fb34d397428f5e/statistik-pendapatan-agustus-2021.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2022, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2022/06/07/762b4c26471da63e74b3c174/statistik-pendapatan-februari-2022-.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2022, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2022/12/07/694d7d6260c74ae507313819/statistik-pendapatan-agustus-2022.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2023, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/06/09/cbaa2fdb7c4cff252995d6ab/statistik-pendapatan-februari-2023.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/12/08/35c68629befbe304809db9fc/statistik-pendapatan-agustus-2023.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2024, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/06/07/2db3f6357ef0359d6657bdc4/statistik-pendapatan-februari-2024.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2024, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/12/09/f26209db25e3b5da9aa58335/statistik-pendapatan-agustus-2024.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2025, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/06/11/d4d33a5452175c1d46d4d338/statistik-pendapatan-februari-2025.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2025, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/12/23/8fc3fabac7285629e83a41d7/statistik-pendapatan-agustus-2025.html", title:"Statistik Pendapatan", lang:"ID", note:"" },
  { year:2022, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/1jhOStLIndDMs1UZsXBDyPo_NEL1MW6a2/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2021, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1AUsmVp3mbdz22OqYRzZXe_VvvW_NK1ep/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2021, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/17ww4VfzZcKFDHB2NXvMy2ANmtQncRrlH/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2020, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1bA3KD1yMlzU6ZhEvznAfK90vooP02hNC/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2020, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/1RO2oQh1RfmbZkX-6fHh6fEYF9EZaZ678/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2019, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1cQGTvxA1lN-JWP0ncSNRUPCblb3JSTS8/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2019, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/1BAqy5k2E6abCVShOZq597XemIbFDPfuQ/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2018, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1F8A-tsO4KxkPvTVSCPAT9BaFe1-rsIO1/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2018, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/1SlpfwVZaKWRldKO3iTCKz8W0SQZWGP4T/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2017, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1KlnM6dP25_Wr3G_HCUThcsiHdVXmkpBA/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2017, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/1MYj-4sLX6mbsZn19nmV_e-nAXPbGn6xs/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2016, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1hXbDxandZes1AOT8j1bReORWwKDqNp-S/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2016, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/1mIWmtoxzdsGZObg1WMZT38vprGmp2ItK/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2015, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1DIKRMFcEEkNSL0wLI195S7dPbvUd2vHl/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2015, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/1fZ2JT8Juq-4DVyTiMW2TnY1xgmKcJnRE/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2014, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1VmVChSiOKiVpP4emjUaxqI9jTWy1JJgX/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2014, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/171QfD3N2FGqqKTWUEsRB0tbOtlEOzw2w/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2014, period:"May", category:"Kuesioner", link:"https://drive.google.com/file/d/1EP95e7jxDmOSkmX08_CLMD-bXtdqLH1F/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2013, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1-hKGIBVAIIOTWC7Ew8RIBh9dLOYDrewJ/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2013, period:"May", category:"Kuesioner", link:"https://drive.google.com/file/d/1YgbJknQeWVMKKfqfFaKjz_e7yXatfalf/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2013, period:"November", category:"Kuesioner", link:"https://drive.google.com/file/d/1w2ckkVLojR3rdDv1NgAt_u90573TROJO/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2012, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1wRTys4wMDhWwlo3GaWz8SAgQZApI9sa6/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2011, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/16kYSSTRh9QG6R2vAxR-N1vtST4jE2lfV/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2010, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/186y5Ih1kFbWdvlyNQkLEFYr9haPhuw7f/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2010, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/1fsG72kV-4h7OcSpvhZbqa7ecPsO196jx/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2009, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/10ESkqEHQIKijw8GOztvFOArFnkXDmvDW/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2008, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/1QTWoisrf_Ifd9M7LsywbxVkEJm-4-I3N/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2006, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/1fVdP7N8QYhZrS-eNKyeqPHIXJ1LuS8To/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2006, period:"November", category:"Kuesioner", link:"https://drive.google.com/file/d/1D1y_U-a2cDc4azoF4CaC62T19GXyTfpx/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2005, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1FAeAt0AJCYadzkaABdvuyOMeInHM005S/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2005, period:"February", category:"Kuesioner", link:"https://drive.google.com/file/d/1aSdUvITzmvwHnSHspYSqR-ybHFITelyl/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2003, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1HPRS2c5y8SBClosF5KIkPvMQLHHrYu8x/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2002, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1P4dREkJhigpwrjLnwYY7TRHWB8fv31jF/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:1998, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1D0_rr4GszoWcIeLaIgugahdf-JDmErgk/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:1997, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1MUjiqs-jrUOMCAU_L5itYWRcvrVRp0wB/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:1996, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1d0H7esk333PU65Aryg3eB1Pl9MYJ5lop/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:1993, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1IYKZCc1kAfPt9CnPHX8XCgpQ5Ejg1rA3/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:1990, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1ALxqpqu03Sp1gA3X-VDBLfvWzi9DYga9/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:1989, period:"August", category:"Kuesioner", link:"https://drive.google.com/file/d/1s5d3DmP-RMV9PCFmp3LT29Wv1OpDxBBJ/preview", title:"Questionnaire", lang:"EN", note:"" },
  { year:2023, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/06/09/d2c2459397c75a14a92742bf/keadaan-pekerja-di-indonesia-februari-2023.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2023, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2023/12/08/1b09be03a0951907a562f755/keadaan-pekerja-di-indonesia-agustus-2023.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2024, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/06/07/bd40ab2fa4fac6c726ab4ad4/keadaan-pekerja-di-indonesia-februari-2024.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2024, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2024/12/09/e1d598ff2e31af0983bb011b/keadaan-pekerja-di-indonesia-agustus-2024.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2025, period:"Februari", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/06/11/8452fd3b9a9d4110ae7a535d/keadaan-pekerja-di-indonesia-februari-2025.html", title:"Keadaan Pekerja", lang:"ID", note:"" },
  { year:2025, period:"Agustus", category:"Publikasi", link:"https://www.bps.go.id/id/publication/2025/12/23/5fe58c9723acafc73fb95bff/keadaan-pekerja-di-indonesia-agustus-2025.html", title:"Keadaan Pekerja", lang:"ID", note:"" }
];
